services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: book_shelves
      POSTGRES_PASSWORD: book_shelves
      POSTGRES_DB: book_shelves
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - "./app:/app"
    environment:
      - FLASK_AUTO_UPGRADE=true
      - SQLALCHEMY_DATABASE_HOST=db
      - SQLALCHEMY_DATABASE_USER=book_shelves
      - SQLALCHEMY_DATABASE_PASSWORD=book_shelves
      - SQLALCHEMY_DATABASE_DATABASE=book_shelves
      - DEBUG=true
    ports:
      - "8080:8080"
    # use this for creating db upgrade scripts; set FLASK_AUTO_UPGRADE to false
    # command: ["flask", "db", "migrate", "-m", "Adding invite codes."]

volumes:
  postgres_data:
