name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - app

env:
    REGION: europe-west3
    REPOSITORY: book-shelves-docker-repo
    PROJECT_ID: book-shelves-477020
    SERVICE_NAME: book-shelves-backend
    IMAGE_NAME: book-shelves-backend
    DB_CONNECTION_NAME: book-shelves-477020:europe-west3:book-shelves

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Docker Image with Layer Cache
        run: |
          docker buildx create --use
          docker buildx build \
            --push \
            --cache-from=type=registry,ref=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/cache:${{ env.IMAGE_NAME }} \
            --cache-to=type=registry,ref=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/cache:${{ env.IMAGE_NAME }},mode=max \
            -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
              --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest \
              --region=${{ env.REGION }} \
              --platform=managed \
              --allow-unauthenticated \
              --service-account=${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT_EMAIL }} \
              --set-secrets=SQLALCHEMY_DATABASE_PASSWORD=db-password:latest \
              --set-secrets=GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest \
              --set-secrets=GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest \
              --set-env-vars=CLOUDSQL_CONNECTION_NAME=${{ env.DB_CONNECTION_NAME }} \
              --add-cloudsql-instances=${{ env.DB_CONNECTION_NAME }}
